dist: trusty
sudo: true
cache:
  directories:
    - $HOME/.cache/apt

language: python
python:
    - "3.6"

env:
  global:
  
    - LATEX_PACKAGES="texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-base texlive-bibtex-extra texlive-extra-utils texlive-font-utils texlive-binaries texlive-generic-extra texlive-generic-recommended texlive-lang-cyrillic texlive-latex-base texlive-latex-extra texlive-latex-recommended texlive-luatex texlive-math-extra texlive-pictures texlive-pstricks texlive-science texlive-xetex cm-super"
  matrix:
    - DIRECTORY="." FILE="main" OUTPUT_NAME="all"
    #- DIRECTORY="template" FILE="main" OUTPUT_NAME="template"
    #- DIRECTORY="NMR-relaxation" FILE="main" OUTPUT_NAME="NMR-relaxation"
    #- DIRECTORY="FTIR" FILE="main" OUTPUT_NAME="FTIR"
    #- DIRECTORY="N2" FILE="main" OUTPUT_NAME="N2"
    #- DIRECTORY="I2" FILE="main" OUTPUT_NAME="I2" 
    # Теория игр
    #- DIRECTORY="game-theory" FILE="main" OUTPUT_NAME="game-theory"
    # Пррограмма теормеха
    #- DIRECTORY="theor-progr" FILE='main' OUTPUT_NAME='theormech-exam-programm-2018'
    # Stat term
    #- DIRECTORY="stat_term/C_H_Cl3" FILE='main' OUTPUT_NAME='stat_term_C_H_Cl3'
    #- DIRECTORY="stat_term/sem_kr" FILE='ans' OUTPUT_NAME='stat_term_sem_control_test'

   
    
before_install:
  - set -o pipefail
  # Setup apt to cache
  - mkdir -p $HOME/.cache/apt/partial
  - sudo rm -rf /var/cache/apt/archives
  - sudo ln -s $HOME/.cache/apt /var/cache/apt/archives
  - sudo chmod -R 777 $HOME/.cache/apt
  - sudo chmod -R 777 /var/cache/apt/archives

install:
  #- sudo apt install python-tornado
  # Install pip packages
  #- pip install -r requirements.txt
  # Setup packages
  - sudo apt-get -qq update && sudo apt-get install -y $LATEX_PACKAGES

script:
  # Check that code compiles
  - export PREV_DIR=$(pwd) &&
    mkdir releases;
    cd $DIRECTORY &&
    if [ $NOTEBOOK ]; then travis_wait 1 jupyter nbconvert --to script $NOTEBOOK_DIR/$NOTEBOOK.ipynb &&
    cd $NOTEBOOK_DIR &&
    ipython $NOTEBOOK.py; fi &&
    cd $PREV_DIR/$DIRECTORY &&
    travis_wait 1 pdflatex -jobname=$OUTPUT_NAME -output-directory $PREV_DIR/releases $FILE.tex &&
    travis_wait 1 pdflatex -jobname=$OUTPUT_NAME -output-directory $PREV_DIR/releases $FILE.tex &&
    cd $PREV_DIR/releases &&
    find . &&
    echo "PREV_DIR is $PREV_DIR"
    
before_deploy:
  - git config --local user.name "alekseik1"
  - git config --local user.email "1alekseik1@gmail.com"
  
deploy:
  provider: releases
  skip-cleanup: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "$PREV_DIR/releases/*.pdf"
  overwrite: true
  on:
    tags: true
